# Generated by Django 5.2.3 on 2025-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True)),
                ('picture', models.CharField()),
                ('viewers', models.IntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('username', models.CharField()),
            ],
        ),
    ]
