# Generated by Django 5.2.3 on 2025-07-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='user_id',
        ),
    ]
